allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true

overrides: {}

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - electron-to-chromium
  - caniuse-lite