# Default values — overridden by the umbrella chart's values.yaml
image:
  repository: ghcr.io/watskebart/stickermap/stickermap-frontend
  tag: main
  pullPolicy: IfNotPresent

replicaCount: 1

tileserverUrl: https://tile.openstreetmap.org/{z}/{x}/{y}.png

resources: {}
