apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  stickermap-realm.json: |
{{ .Files.Get "files/stickermap-realm.json" | indent 4 }}
