// Generated by general/scripts/bump-version.py from the `### Highlights`
// sections of CHANGELOG.md. Do not edit by hand.

export interface ChangelogRelease {
  version: string;
  date?: string;
  items: string[];
}

export const CHANGELOG_DATA: ChangelogRelease[] = [
  {
    version: '1.24.0',
    date: '2026-08-02',
    items: [
      '<strong>The "what\'s new" dialog is now a short summary in plain language.</strong> Each release opens with a handful of bullets about what changed for you, instead of the full technical list grouped under Added, Changed and Fixed. The complete technical record is still on GitHub for anyone who wants to read it.',
      '<strong>Older releases were rewritten the same way</strong>, so the history in the dialog reads consistently all the way back to the first release.',
    ],
  },
  {
    version: '1.23.0',
    date: '2026-08-02',
    items: [
      '<strong>Add a note to your stickers.</strong> An optional field for the story behind a sticker — "posted during the X festival", "second attempt, the first one got peeled off". Up to 256 characters. Fill it in when you upload, or add it later by editing the sticker from the map or the sticker overview. Notes also show up in CSV and GeoJSON exports.',
      '<strong>Notes are for signed-in users only.</strong> Visitors who are not logged in never see them, the same way poster names and dates are already hidden.',
      '<strong>A new disclaimer rule about sensitive information</strong>, plus a reminder and a live character counter on the note fields themselves.',
    ],
  },
  {
    version: '1.22.1',
    date: '2026-08-01',
    items: [
      'Security updates to third-party libraries. Nothing changes in how the app works.',
    ],
  },
  {
    version: '1.22.0',
    date: '2026-08-01',
    items: [
      '<strong>A newer map engine.</strong> The map now runs on MapLibre 6, with faster rendering.',
      '<strong>Updated to Angular 22</strong> under the hood. Nothing changes on screen.',
      '<strong>The map no longer works in very old browsers.</strong> It now needs WebGL2, which every major browser has supported since 2021. If yours is older, the rest of StickerMap still works — only the map will fail to load.',
    ],
  },
  {
    version: '1.21.5',
    date: '2026-07-21',
    items: [
      'Security updates to the image-processing and build libraries. Nothing changes in how the app works.',
    ],
  },
  {
    version: '1.21.4',
    date: '2026-06-24',
    items: [
      'Security updates to third-party libraries. Nothing changes in how the app works.',
    ],
  },
  {
    version: '1.21.3',
    date: '2026-06-17',
    items: [
      'Security updates to third-party libraries. Nothing changes in how the app works.',
    ],
  },
  {
    version: '1.21.2',
    date: '2026-06-16',
    items: [
      '<strong>Fixes the 1.21.1 release never shipping.</strong> A supply-chain check blocked the frontend image from publishing, so 1.21.2 is the first build that actually contains the 1.21.1 changes.',
    ],
  },
  {
    version: '1.21.1',
    date: '2026-06-16',
    items: [
      'Security updates to third-party libraries. Nothing changes in how the app works.',
    ],
  },
  {
    version: '1.21.0',
    date: '2026-05-30',
    items: [
      '<strong>For self-hosters:</strong> plain HTTP traffic is now redirected to HTTPS automatically in the Helm chart. Nothing changes in the app itself.',
    ],
  },
  {
    version: '1.20.0',
    date: '2026-05-29',
    items: [
      '<strong>StickerMap now speaks Dutch and English.</strong> Switch language from the sidebar at any time — no reload needed, and your choice is remembered. Every screen is translated.',
    ],
  },
  {
    version: '1.19.0',
    date: '2026-05-26',
    items: [
      'Internal cleanup and documentation updates. Nothing changes on screen.',
    ],
  },
  {
    version: '1.18.0',
    date: '2026-05-22',
    items: [
      '<strong>"Date unknown" for stickers.</strong> When you don\'t know when a sticker was posted, tick the box on the upload or edit form and it shows as "Unknown" instead of a made-up date.',
      '<strong>Moving a sticker now shows where it was.</strong> The old location stays visible as a blue marker while you pick the new one.',
      '<strong>You are signed out when you close your browser again.</strong> Sessions no longer persist across browser restarts, reversing the change made in 1.13.0.',
      'More sensible default zoom levels, a tidier sidebar menu, and fixes to the manual coordinate field and some small layout glitches in the upload and edit forms.',
    ],
  },
  {
    version: '1.17.2',
    date: '2026-05-17',
    items: [
      '<strong>For self-hosters:</strong> Helm chart image naming and tag fixes. Nothing changes in the app.',
    ],
  },
  {
    version: '1.17.1',
    date: '2026-05-17',
    items: [
      '<strong>For self-hosters:</strong> the Helm chart renders without errors when optional values are left unset. Nothing changes in the app.',
    ],
  },
  {
    version: '1.17.0',
    date: '2026-05-16',
    items: [
      '<strong>Switch between street, satellite, and terrain maps.</strong> A new control in the bottom-left corner of the map; your choice is remembered for next time.',
      '<strong>The category filter no longer covers the map controls on a phone.</strong>',
      '<strong>For self-hosters:</strong> breaking Helm chart changes — the chart no longer ships a database or Keycloak, and the tile server URL is now three separate variables. Read the details below before upgrading.',
    ],
  },
  {
    version: '1.16.0',
    date: '2026-05-16',
    items: [
      '<strong>A maintenance page for admins.</strong> See how many stickers are missing photos, thumbnails, or location data, and run cleanup jobs: generate missing thumbnails, shrink oversized photos, strip camera data from stored images, and delete files no longer linked to any sticker.',
      '<strong>The map loads faster</strong> — map tiles and sticker data are now fetched only when needed.',
      '<strong>The sticker overview remembers your page size</strong> and can now be sorted by category.',
    ],
  },
  {
    version: '1.15.0',
    date: '2026-05-16',
    items: [
      '<strong>Mark a sticker as private</strong> so it stays hidden from visitors who are not signed in. Private stickers carry a lock icon on the map and in the overview.',
      '<strong>Export the sticker list</strong> as CSV or GeoJSON (editors and admins).',
      '<strong>Click a photo in a map popup to open it full size</strong>, even when you are not signed in.',
    ],
  },
  {
    version: '1.14.0',
    date: '2026-05-14',
    items: [
      '<strong>Stickers now have categories.</strong> Pick one when uploading or editing, and sort the overview by it. Moderators manage the list of categories from a dedicated page.',
    ],
  },
  {
    version: '1.13.0',
    date: '2026-05-14',
    items: [
      '<strong>You stay signed in between browser sessions.</strong> (Reversed again in 1.18.0.)',
    ],
  },
  {
    version: '1.12.0',
    date: '2026-05-10',
    items: [
      '<strong>Archive stickers instead of deleting them</strong> (editors and admins).',
      '<strong>Sticker details in map popups are now shown only to signed-in users.</strong>',
    ],
  },
  {
    version: '1.11.0',
    date: '2026-05-09',
    items: [
      '<strong>Report a sticker that is no longer there.</strong> If you find that a sticker has been removed, you can now report it so the map stays accurate.',
      '<strong>No more sideways scrolling</strong> in the sticker overview on a phone.',
    ],
  },
  {
    version: '1.10.1',
    date: '2026-05-06',
    items: [
      '<strong>Sidebar tooltips now appear whether the menu is expanded or collapsed.</strong>',
    ],
  },
  {
    version: '1.10.0',
    date: '2026-05-05',
    items: [
      '<strong>Rotate sticker photos.</strong> Photos that come out sideways can be turned the right way up, and new uploads are rotated automatically based on how the camera was held.',
      '<strong>A proper mobile layout</strong> across the whole app.',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-05-02',
    items: [
      '<strong>A faster app when several people use it at once.</strong> Nothing changes on screen.',
    ],
  },
  {
    version: '1.8.0',
    date: '2026-04-19',
    items: [
      '<strong>See what\'s new after an update.</strong> A dialog with the latest changes appears on your first visit after a new version ships.',
      '<strong>Share a map view.</strong> The map position and zoom are now part of the address bar, so you can bookmark a spot or send someone a link that opens exactly where you were.',
    ],
  },
  {
    version: '1.7.0',
    date: '2026-04-18',
    items: [
      '<strong>New accounts can view the map straight away</strong> — every new user now gets viewer access automatically.',
      '<strong>For self-hosters:</strong> roles moved from realm scope to client scope in Keycloak, with a new group structure. Existing installs need to be updated.',
    ],
  },
  {
    version: '1.6.2',
    date: '2026-04-18',
    items: [
      '<strong>A more reliable sign-in</strong>, rebuilt on a standards-compliant OpenID Connect library.',
      '<strong>For self-hosters:</strong> photo size and quality limits are now configurable.',
    ],
  },
  {
    version: '1.6.1',
    date: '2026-04-14',
    items: [
      '<strong>Signing in on a phone works again.</strong>',
      '<strong>For self-hosters:</strong> the Helm chart is now a single flat chart and requires Helm v4.',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-04-10',
    items: [
      '<strong>Your camera data stays private.</strong> Everything except the location is now stripped from uploaded photos — camera model, serial number, timestamps.',
      '<strong>Uploads are smaller and faster.</strong> Photos are resized and compressed on the server before being stored.',
      '<strong>Sticker details in map popups now depend on whether you are signed in.</strong>',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-04-08',
    items: [
      '<strong>A short disclaimer before your first upload</strong>, covering what is and is not OK to post.',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-04-07',
    items: [
      '<strong>A sticker\'s date is now read from the photo even when it has no location data.</strong>',
      '<strong>Empty files and photos without location no longer break the upload</strong> — you get a clear error instead.',
      '<strong>An F-35 cursor that banks as you move the mouse</strong> across the map.',
    ],
  },
  {
    version: '1.3.5',
    date: '2026-04-01',
    items: [
      '<strong>The login screen now always appears</strong> instead of trying to sign you in silently first.',
    ],
  },
  {
    version: '1.3.4',
    date: '2026-04-01',
    items: [
      '<strong>Uploader statistics show real names</strong> instead of usernames.',
    ],
  },
  {
    version: '1.3.3',
    date: '2026-03-31',
    items: [
      '<strong>Signing in works on mobile browsers again.</strong>',
    ],
  },
  {
    version: '1.3.2',
    date: '2026-03-22',
    items: [
      'Internal changes to how sign-in tokens are handled. Nothing changes on screen.',
    ],
  },
  {
    version: '1.3.1',
    date: '2026-03-22',
    items: [
      '<strong>Dark mode now covers the screens it previously missed.</strong>',
      '<strong>Who uploaded a sticker is only shown to signed-in users.</strong>',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-03-18',
    items: [
      '<strong>For self-hosters:</strong> container image improvements and a renamed <code>FQDN</code> → <code>PUBLIC_URL</code> environment variable. Nothing changes in the app.',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-03-15',
    items: [
      '<strong>A sticker overview page</strong> with a sortable, filterable table, inline editing, and bulk delete.',
      '<strong>Dark mode</strong>, with a toggle that remembers your choice.',
      '<strong>Statistics on the landing page</strong> — how many stickers there are in total and per uploader.',
      '<strong>The map remembers where you were.</strong> The address bar updates as you pan and zoom, so bookmarks and shared links reopen the same view.',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-03-14',
    items: [
      '<strong>A refreshed interface</strong> built on Angular Material.',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-03-08',
    items: [
      '<strong>The first release of StickerMap.</strong> Pin stickers on an interactive map, upload a photo and have its location filled in automatically, and sign in to add and manage your own.',
    ],
  },
];
