apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backend-uploads
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.uploads.storage.size }}
  {{- if .Values.uploads.storage.storageClassName }}
  storageClassName: {{ .Values.uploads.storage.storageClassName }}
  {{- end }}
